apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ticket-system
  labels:
    app: frontend
    tier: presentation
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
