apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: default
  labels:
    app: core-api
spec:
  selector:
    app: core-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer