apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: ticket-system
  labels:
    app: core-api
spec:
  selector:
    app: core-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
